parameters:
    karser.main_sms.model.class: Karser\MainSMSBundle\Model\MainSMS
    karser.handler.main_sms.class: Karser\MainSMSBundle\Handler\MainSMSHandler

services:
    karser.main_sms.model:
        class: %karser.main_sms.model.class%
        arguments: [ %main_sms.project%, %main_sms.key%, %main_sms.use_ssl%, %main_sms.test_mode% ]

    karser.handler.main_sms:
        class: %karser.handler.main_sms.class%
        arguments: [ @karser.main_sms.model ]
        tags:
          - {name: "sms.handler"}
